print(True)
print(False)
print(1.2 + 1)
print('Aqui eu falo a minha língua!')
print("Também funciona.")
print('Você é ' + 3 * 'muito ' + 'legal!')
# print(3 + '3') -> ambiguidade
print([1, 2, 3])
print({'nome': 'Diego', 'idade': 40})
print(None)
